# Generated by Django 5.2.12 on 2026-03-29 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_urlcheck"),
    ]

    operations = [
        migrations.CreateModel(
            name="UrlPing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_code", models.IntegerField()),
                ("time", models.DateTimeField(auto_now_add=True)),
                (
                    "url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pings",
                        to="api.url",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="UrlCheck",
        ),
    ]
