# Generated by Django 5.2.12 on 2026-03-31 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_urlping_delete_urlcheck"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="url",
            field=models.URLField(max_length=100),
        ),
    ]
