# Generated by Django 5.2.12 on 2026-04-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_url_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="urlping",
            name="error_snapshot",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
